### ISSUE TITLE
create collections or others failed

### ISSUE THREAD

**Issue by syj121** [patterns-ai-core/milvus#8]
Faraday::Error: :json is not registered on Faraday::Request

**Comment by andreibondarev** [comment]
@syj121 Which version of the gem are you running? Could you please paste the code you're running? Also -- I would suggest using the [Langchain.rb](https://github.com/andreibondarev/langchainrb) gem.

**Comment by syj121** [comment]
version0.9.1。just past the example code。
thank you for your recommond。i will have a try

> @syj121 Which version of the gem are you running? Could you please paste the code you're running? Also -- I would suggest using the [Langchain.rb](https://github.com/andreibondarev/langchainrb) gem.

**Comment by andreibondarev** [comment]
@syj121 Could you please test out 0.92 real quick?

**Comment by syj121** [comment]
> @syj121 Could you please test out 0.92 real quick?
 0.92 seems to require higher version for 'Faraday', and it conflicts with other gems. so i haven‘t test it
