### ISSUE TITLE
Milvus Datatypes constant has wrong elements

### ISSUE THREAD

**Issue by aothelal** [patterns-ai-core/milvus#9]
Version: 0.9.1

The source code has this as the elements:
```
  {
    "boolean" => 1,
    "int8" => 2,
    "int16" => 3,
    "int32" => 4,
    "int64" => 5,
    "float" => 10,
    "double" => 11,
    "string" => 20,
    "varchar" => 21,
    "binary_vector" => 100,
    "float_vector" => 101
  }
```

But these are the values within a Pry session:
```
{"boolean"=>1,
 "int8"=>2,
 "int16"=>3,
 "int32"=>4,
 "int64"=>5,
 "float"=>10,
 "double"=>11,
 "string"=>20,
 "varchar"=>21,
 "binary_vector"=>101,
 "float_vector"=>102}
```

I think the Gem just needs to be updated on RubyGems as I found the issue inside the source code after a gem unpack, for now I used the integer values instead of the identifiers.

**Comment by andreibondarev** [comment]
@aothelal Would you be open to updating the gem?

**Comment by mensfeld** [comment]
I encountered same issue. So is 101 a binary?

**Comment by andreibondarev** [comment]
All of the constants should be up to date now: https://github.com/patterns-ai-core/milvus/blob/main/lib/milvus/constants.rb
